### ISSUE TITLE
Bugs laravel

### ISSUE THREAD

**Issue by matbandeli** [thegazou/Tsuro-Online#4]
J'ai parfois un bug que je ne comprends pas sur Laravel :

RuntimeException in EncryptionServiceProvider.php line 29: No supported encrypter found. The cipher and / or key length are invalid. 
1.  in EncryptionServiceProvider.php line 29
2.  at EncryptionServiceProvider->Illuminate\Encryption{closure}(object(Application), array()) in Container.php line 734
3.  at Container->build(object(Closure), array()) in Container.php line 627
4.  at Container->make('encrypter', array()) in Application.php line 674
5.  at Application->make('Illuminate\Contracts\Encryption\Encrypter') in Container.php line 838
6.  at Container->resolveClass(object(ReflectionParameter)) in Container.php line 801
7.  at Container->getDependencies(array(object(ReflectionParameter)), array()) in Container.php line 772
8.  at Container->build('App\Http\Middleware\EncryptCookies', array()) in Container.php line 627
9.  at Container->make('App\Http\Middleware\EncryptCookies', array()) in Application.php line 674
10. at Application->make('App\Http\Middleware\EncryptCookies') in Pipeline.php line 123
11. at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in CheckForMaintenanceMode.php line 42
12. at CheckForMaintenanceMode->handle(object(Request), object(Closure))
13. at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
14. at Pipeline->Illuminate\Pipeline{closure}(object(Request))
15. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
16. at Pipeline->then(object(Closure)) in Kernel.php line 122
17. at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
18. at Kernel->handle(object(Request)) in index.php line 54

RuntimeException in EncryptionServiceProvider.php line 29: No supported encrypter found. The cipher and / or key length are invalid. 
1.  in EncryptionServiceProvider.php line 29
2.  at EncryptionServiceProvider->Illuminate\Encryption{closure}(object(Application), array()) in Container.php line 734
3.  at Container->build(object(Closure), array()) in Container.php line 627
4.  at Container->make('encrypter', array()) in Application.php line 674
5.  at Application->make('Illuminate\Contracts\Encryption\Encrypter') in Container.php line 838
6.  at Container->resolveClass(object(ReflectionParameter)) in Container.php line 801
7.  at Container->getDependencies(array(object(ReflectionParameter)), array()) in Container.php line 772
8.  at Container->build('App\Http\Middleware\EncryptCookies', array()) in Container.php line 627
9.  at Container->make('App\Http\Middleware\EncryptCookies', array()) in Application.php line 674
10. at Application->make('App\Http\Middleware\EncryptCookies') in Kernel.php line 142
11. at Kernel->terminate(object(Request), object(Response)) in index.php line 58

**Comment by greut** [comment]
@matbandeli http://laravel-recipes.com/recipes/283/generating-a-new-application-key

**Comment by matbandeli** [comment]
Extrait du fichier log, après un test : ping 1 => ping 2 => ping 1 => … (5-6 fois), puis erreur
Pourtant j'ai fait la manip :  php artisan key:generate

[2015-11-30 22:04:54] local.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:29
Stack trace:
#0 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption{closure}(Object(Illuminate\Foundation\Application), Array)
#1 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build(Object(Closure), Array)
#2 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(838): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(801): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(772): Illuminate\Container\Container->getDependencies(Array, Array)
#6 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(123): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#13 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 C:\laragon\www\tsuro2\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-11-30 22:04:54] local.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:29
Stack trace:
#0 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption{closure}(Object(Illuminate\Foundation\Application), Array)
#1 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build(Object(Closure), Array)
#2 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(838): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(801): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(772): Illuminate\Container\Container->getDependencies(Array, Array)
#6 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 C:\laragon\www\tsuro2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 C:\laragon\www\tsuro2\public\index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}

**Comment by greut** [comment]
@matbandeli oui oui, faites ceci.

``` shell
$ cat .env | grep APP_KEY
APP_KEY=...
```

**Comment by matbandeli** [comment]
cat .env | grep APP_KEY
APP_KEY=B9woHfc7k8PYKxl4yevRS5ud5KoMoDzr

**Comment by greut** [comment]
@matbandeli Okay, autre piste.

``` diff
- 'cipher' => MCRYPT_RIJNDAEL_128,
+ 'cipher' => 'AES-256-CBC',
```

Et une autre:

``` shell
$ php -m | grep ^m
mbstring
mcrypt
mhash
mysqlnd
```

![tsuro](https://cloud.githubusercontent.com/assets/1388/11501031/4e55edf4-9831-11e5-9521-2d11a4d83dab.png)

**Comment by matbandeli** [comment]
php -m | grep ^m  
bcmath  
dom  
libxml  
mbstring  
mcrypt  
memcache  
mhash  
mysql  
mysqli  
mysqlnd  
pdo_mysql  
SimpleXML  
xml  
xmlreader  
xmlrpc  
xmlwriter

et pour la première idée je dois changer ces lignes dans .env?

**Comment by greut** [comment]
@matbandeli 

``` shell
$ ack cipher
config/app.php
83:    'cipher' => 'AES-256-CBC',
```

**Comment by matbandeli** [comment]
La commande ack n'est pas reconnue. 

J'ai fait : 

```
cat config/app.php | grep cipher
'cipher' => 'AES-256-CBC',
```

**Comment by greut** [comment]
@matbandeli le problème est dans tsuro ou tsuro2?

**Comment by greut** [comment]
@matbandeli tsuro2 étant donné que tsuro est un laravel 5.0.x

Un moyen de débugger ça est de voir ce qu'il se passe ici:
https://github.com/laravel/framework/blob/076a054b6c78888acb3d0b93030402dbf736d824/src/Illuminate/Encryption/EncryptionServiceProvider.php

Vous pouvez modifier le fichier dans `vendors/laravel/framework/src/...` Dans le pire des cas, vous le supprimez et le recréez.
